/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for pkcs8
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder pkcs8_decoder;

extern int pkcs8_note_OID(void *, size_t, unsigned char, const void *, size_t);
extern int pkcs8_note_algo(void *, size_t, unsigned char, const void *, size_t);
extern int pkcs8_note_key(void *, size_t, unsigned char, const void *, size_t);
extern int pkcs8_note_version(void *, size_t, unsigned char, const void *, size_t);

