'\" t
.\"     Title: gpscat
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 16 Nov 2006
.\"    Manual: GPSD Documentation
.\"    Source: The GPSD Project
.\"  Language: English
.\"
.TH "GPSCAT" "1" "16 Nov 2006" "The GPSD Project" "GPSD Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gpscat \- dump the output from a GPS
.SH "SYNOPSIS"
.HP \w'\fBgpscat\fR\ 'u
\fBgpscat\fR [\-s\ \fIspeed\fR] [\-p] [\-t] [\-D\ \fIdebuglevel\fR] \fIfile\-or\-serial\-port\fR
.SH "DESCRIPTION"
.PP
gpscat
is a simple program for logging and packetizing GPS data streams\&. It takes input from a specified file or serial device (presumed to have a GPS attached) and reports to standard output\&. The program runs until end of input or it is interrupted by ^C or other means\&. It does not terminate on a bad packet; this is intentional\&.
.PP
In raw mode (the default)
gpscat
simply dumps its input to standard output\&. Nonprintable characters other than ASCII whitespace are rendered as hexadecimal string escapes\&.
.PP
In packetizing mode,
gpscat
uses the same code as
\fBgpsd\fR(8)\*(Aqs packet sniffer to break the input into packets\&. Packets are reported one per line; line breaks in the packets themselves are escaped\&.
.PP
This program is useful as a sanity checker when examining a new device\&. It can be used as a primitive NMEA logger, but beware that (a) interrupting it likely to cut off output in mid\-sentence, and (b) to avoid displaying incomplete NMEA sentences right up next to shell prompts that often contain a $, raw mode always emits an extra final linefeed\&.
.PP
Also, be aware that packetizing mode will produce useless results \(em probably consuming the entirety of input and appearing to hang \(em if it is fed data that is not a sequence of packets of one of the known types\&.
.PP
The program accepts the following options:
.PP
\-p
.RS 4
Invoke packetizer mode\&.
.RE
.PP
\-s
.RS 4
Set the port\*(Aqs baud rate (and optionally its parity and stop bits) before reading\&. Argument should begin with one of the normal integer baud rates (300, 1200, 4800, 9600, 19200, 38400, etc\&.)\&. It may be followed by an optional suffix [NOE][12] to set parity (None, Odd, Even) and stop bits (1 or 2)\&.
.RE
.PP
\-t
.RS 4
Invoke packetizer mode, with the packet type and length (in parentheses) reported before a colon and space on each line\&.
.RE
.PP
\-D
.RS 4
In packetizer mode, enable progress messages from the packet getter\&. Probably only of interest to developers testing packet getter changes\&. Higher arguements to D produce more output\&.
.RE
.PP
\-h
.RS 4
Display program usage and exit\&.
.RE
.PP
Specifying \-s 4800N1 is frequently helpful with unknown devices\&.
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBgps\fR(1),
\fBlibgps\fR(3),
\fBlibgpsmm\fR(3),
\fBgpsfake\fR(1)\&.
\fBgpsprof\fR(1),
\fBgpsctl\fR(1),
\fBgpsdctl\fR(8),
\fBgpsmon\fR(1)\&.
.SH "AUTHOR"
.PP
Eric S\&. Raymond
<esr@thyrsus\&.com>\&.
