'\" t
.\"     Title: gpsfake
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12 Feb 2005
.\"    Manual: GPSD Documentation
.\"    Source: The GPSD Project
.\"  Language: English
.\"
.TH "GPSFAKE" "1" "12 Feb 2005" "The GPSD Project" "GPSD Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gpsfake \- test harness for gpsd, simulating a GPS
.SH "SYNOPSIS"
.HP \w'\fBgpsfake\fR\ 'u
\fBgpsfake\fR [\-1] [\-h] [\-b] [\-c\ \fIinterval\fR] [\-i] [\-D\ \fIdebuglevel\fR] [\-l] [\-m\ \fImonitor\fR] [\-g] [\-G] [\-n] [\-o\ \fIoptions\fR] [\-p] [\-P\ \fIport\fR] [\-q] [\-r\ \fIinitcmd\fR] [\-s\ \fIspeed\fR] [\-S] [\-u] [\-t] [\-T] [\-v] [\-W\ \fItimeout\fR] [\fIlogfile\fR...]
.SH "DESCRIPTION"
.PP
gpsfake
is a test harness for
gpsd
and its clients\&. It opens a pty (pseudo\-TTY), launches a
gpsd
instance that thinks the slave side of the pty is its GPS device, and repeatedly feeds the contents of one or more test logfiles through the master side to the GPS\&. If there are multiple logfiles, sentences from them are interleaved in the order the files are specified\&.
.PP
gpsfake
does not require root privileges, and can be run concurrently with a production
gpsd
instance without causing problems\&.
.PP
The logfiles may contain packets in any supported format, including in particular NMEA, SiRF, TSIP, or Zodiac\&. Leading lines beginning with # will be treated as comments and ignored, except in the following special cases:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a comment of the form #Date: yyyy\-mm\-dd (ISO8601 date format) may be used to set the initial date for the log\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a comment of the form #Serial: [0\-9]* [78][NOE][12] may be used to set serial parameters for the log \- baud rate, word length, stop bits\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a comment of the form #Transport: UDP may be used to fake a UDP source rather than the normal pty\&.
.RE
.PP
The
gpsd
instance is run in foreground\&. The thread sending fake GPS data to the daemon is run in background\&.
.SH "OPTIONS"
.PP
With the \-1 option, the logfile is interpreted once only rather than repeatedly\&. This option is intended to facilitate regression testing\&.
.PP
The
\fB\-b\fR
enables a twirling\-baton progress indicator on standard error\&. At termination, it reports elapsed time\&.
.PP
The
\fB\-c\fR
sets the delay between sentences in seconds\&. Fractional values of seconds are legal\&. The default is zero (no delay)\&.
.PP
The
\fB\-l\fR
makes the program dump a line or packet number just before each sentence is fed to the daemon\&. If the sentence is textual (e\&.g\&. NMEA), the text is dumped as well\&. If not, the packet will be dumped in hexadecimal (except for RTCM packets, which aren\*(Aqt dumped at all)\&. This option is useful for checking that gpsfake is getting packet boundaries right\&.
.PP
The
\fB\-i\fR
is for single\-stepping through logfiles\&. It dumps the line or packet number (and the sentence if the protocol is textual) followed by "? "\&. Only when the user keys Enter is the line actually fed to
gpsd\&.
.PP
The
\fB\-m\fR
specifies a monitor program inside which the daemon should be run\&. This option is intended to be used with
\fBvalgrind\fR(1),
\fBgdb\fR(1)
and similar programs\&.
.PP
The
\fB\-g\fR
and
\fB\-G\fR
options use the monitor facility to run the
gpsd
instance within gpsfake under control of gdb or lldb, respectively\&. They also disable the timeout on daemon inactivity, to allow for breakpointing\&. If necessary, the timeout can be reenabled by a subsequent
\fB\-W\fR\&.
.PP
The
\fB\-o\fR
specifies options to pass to the daemon\&. The \-n option passes \-n to start the daemon reading the GPS without waiting for a client (equivalent to \-o "\-n")\&. The
\fB\-D\fR
passes a \-D option to the daemon: thus \-D 4 is shorthand for \-o "\-D 4"\&.
.PP
The \-p ("pipe") option sets watcher mode and dumps the NMEA and GPSD notifications generated by the log to standard output\&. This is useful for regression\-testing\&.
.PP
The \-P ("port") option sets the daemon\*(Aqs listening port\&.
.PP
The
\fB\-q\fR
tells gpsfake to suppress normal progress output and thus act in a quiet manner\&.
.PP
The
\fB\-r\fR
specifies an initialization command to use in pipe mode\&. The default is
\fB?WATCH={"enable":true,"json":true}\fR\&.
.PP
The
\fB\-s\fR
sets the baud rate for the slave tty\&. The default is 4800\&.
.PP
The option \-S tells gpsfake to insert realistic delays in the test input rather than trying to stuff it through the daemon as fast as possible\&. This will make the test(s) run much slower, but avoids flaky failures due to machine lode and possible race conditions in the pty layer\&.
.PP
The
\fB\-t\fR
forces the test framework to use TCP rather than pty devices\&. Besides being a test of TCP source handling, this may be useful for testing from within chroot jails where access to pty devices is locked out\&.
.PP
The
\fB\-T\fR
makes
gpsfake
print some system information and then exits\&.
.PP
The
\fB\-u\fR
forces the test framework to use UDP rather than pty devices\&. Besides being a test of UDP source handling, this may be useful for testing from within chroot jails where access to pty devices is locked out\&.
.PP
The
\fB\-v\fR
enables verbose progress reports to stderr\&. It is mainly useful for debugging
gpsfake
itself\&.
.PP
The
\fB\-W\fR
("wait") option sets the timeout on daemon inactivity, in seconds\&. The default timeout is 60 seconds, and a value of 0 suppresses the timeout altogether\&. Note that the actual timeout is longer due to internal delays, typically by about 20 seconds\&.
.PP
The
\fB\-x\fR
dumps packets as
gpsfake
gathers them\&. It is mainly useful for debugging
gpsfake
itself\&.
.PP
The
\fB\-h\fR
makes
gpsfake
print a usage message and exit\&.
.PP
The argument must be the name of a file containing the data to be cycled at the device\&.
gpsfake
will print a notification each time it cycles\&.
.PP
Normally, gpsfake creates a pty for each logfile and passes the slave side of the device to the daemon\&. If the header comment in the logfile contains the string "UDP", packets are instead shipped via UDP port 5000 to the address 192\&.168\&.0\&.1\&.255\&. You can monitor them with this:
\fBtcpdump \-s0 \-n \-A \-i lo udp and port 5000\fR\&.
.SH "MAGIC COMMENTS"
.PP
Certain magic comments in test load headers can change the conditions of the test\&. These are:
.PP
Serial:
.RS 4
May contain a serial\-port setting such as 4800 7N2 \- baud rate followed by 7 or 8 for byte length, N or O or E for parity and 1 or 2 for stop bits\&. The test is run with those settings on the slave port that the daemon sees\&.
.RE
.PP
Transport:
.RS 4
Values \*(AqTCP\*(Aq and \*(AqUDP\*(Aq force the use of TCP and UDP feeds respectively (the default is a pty)\&.
.RE
.PP
Delay\-Cookie:
.RS 4
Must be followed by two whitespace\-separated fields, a delimiter character and a numeric delay in seconds\&. Instead of being broken up by packet boundaries, the test load is split on the delimiters\&. The delay is performed after each feed\&. Can be useful for imposing write boundaries in the middle of packets\&.
.RE
.SH "CUSTOM TESTS"
.PP
gpsfake
is a trivial wrapper around a Python module, also named gpsfake, that can be used to fully script sessions involving a
gpsd
instance, any number of client sessions, and any number of fake GPSes feeding the daemon instance with data from specified sentence logs\&.
.PP
Source and embedded documentation for this module is shipped with the
gpsd
development tools\&. You can use it to torture\-test either
gpsd
itself or any
gpsd\-aware client application\&.
.PP
Logfiles for the use with
gpsfake
can be retrieved using
gpspipe,
gpscat, or
gpsmon
from the gpsd distribution, or any other application which is able to create a compatible output\&.
.PP
If
gpsfake
exits with "Cannot execute gpsd: executable not found\&." the environment variable GPSD_HOME can be set to the path where gpsd can be found\&. (instead of adding that folder to the PATH environment variable
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBgps\fR(1),
\fBlibgps\fR(3),
\fBlibgpsmm\fR(3),
\fBgpsctl\fR(1),
\fBgpspipe\fR(1),
\fBgpsprof\fR(1)
\fBgpsmon\fR(1)\&.
.SH "AUTHOR"
.PP
Eric S\&. Raymond
<esr@thyrsus\&.com>\&.
