'\" t
.\"     Title: gpxlogger
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05 Mar 2017
.\"    Manual: GPSD Documentation
.\"    Source: The GPSD Project
.\"  Language: English
.\"
.TH "GPXLOGGER" "1" "05 Mar 2017" "The GPSD Project" "GPSD Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gpxlogger \- Tool to connect to gpsd and generate a GPX file
.SH "SYNOPSIS"
.HP \w'\fBgpxlogger\fR\ 'u
\fBgpxlogger\fR [\-D\ \fIdebug\-level\fR] [\-d] [\-e\ \fIexport\-method\fR] [\-f\ \fIfilename\fR] [\-l] [\-m\ \fIminmove\fR] [\-h] [\-V] [\-i\ \fItrack\ timeout\fR] [\fIserver\fR [\fI:port\fR [\fI:device\fR]]]
.SH "DESCRIPTION"
.PP
This program collects fixes from
gpsd
and logs them to standard output in GPX, an XML profile for track logging\&.
.PP
The output may be composed of multiple tracks\&. A new track is created if there\*(Aqs no fix written for an interval specified by the
\fB\-i\fR
and defaulting to 5 seconds\&.
.PP
gpxlogger
can use any of the export methods that
gpsd
supports\&. For a list of these methods, use the
\fB\-l\fR\&. To force the method, give the
\fB\-e\fR
one of the colon\-terminated method names from the
\fB\-l\fR
table\&.
.SH "OPTIONS"
.PP
The
\fB\-h\fR
option causes
gpxlogger
to emit a summary of its options and then exit\&.
.PP
The
\fB\-V\fR
option causes
gpxlogger
to dump the package version and exit\&.
.PP
The
\fB\-D\fR
option sets a debug level; it is primarily for use by GPSD developers\&. It enables various progress messages to standard error\&.
.PP
The
\fB\-d\fR
option tells
gpxlogger
to run as a daemon in background\&. It requires the
\fB\-f\fR
option, which directs output to a specified logfile\&.
.PP
The
\fB\-m\fR
option sets a minimum move distance in meters (it may include a fractional decimal part)\&. Motions shorter than this will not be logged\&.
.PP
The
\fB\-r\fR
option tells
gpxlogger
to retry when GPSd loses the fix\&. Without
\fB\-r\fR,
gpxlogger
would quit in this case\&.
.PP
If D\-Bus support is available on the host, GPSD is configured to use it, and
\fB\-e dbus\fR
is specified, this program listens to DBUS broadcasts from
gpsd
via org\&.gpsd\&.fix\&.
.PP
With
\fB\-e sockets\fR, or if sockets is the method defaulted to, you may give a server\-port\-device specification as arguments\&.
.PP
The sockets default is to all devices on the localhost, using the default GPSD port 2947\&. An optional argument to any client may specify a server to get data from\&. A colon\-separated suffix is taken as a port number\&. If there is a second colon\-separated suffix, that is taken as a specific device name to be watched\&. However, if the server specification contains square brackets, the part inside them is taken as an IPv6 address and port/device suffixes are only parsed after the trailing bracket\&. Possible cases look like this:
.PP
localhost:/dev/ttyS1
.RS 4
Look at the default port of localhost, trying both IPv4 and IPv6 and watching output from serial device 1\&.
.RE
.PP
example\&.com:2317
.RS 4
Look at port 2317 on example\&.com, trying both IPv4 and IPv6\&.
.RE
.PP
71\&.162\&.241\&.5:2317:/dev/ttyS3
.RS 4
Look at port 2317 at the specified IPv4 address, collecting data from attached serial device 3\&.
.RE
.PP
[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:2317:/dev/ttyS5
.RS 4
Look at port 2317 at the specified IPv6 address, collecting data from attached serial device 5\&.
.RE
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBgps\fR(1)
\fBgpspipe\fR(1)
.SH "AUTHORS"
.PP
Amaury Jacquot
<sxpert@sxpert\&.org>
& Petter Reinholdtsen
<pere@hungry\&.com>
& Chris Kuethe
<chris\&.kuethe@gmail\&.com>
