'\" t
.\"     Title: libgpsmm
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 13 May 2005
.\"    Manual: GPSD Documentation
.\"    Source: The GPSD Project
.\"  Language: English
.\"
.TH "LIBGPSMM" "3" "13 May 2005" "The GPSD Project" "GPSD Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
libgpsmm, libQgpsmm \- C++ and QT class wrapper for the GPS daemon
.SH "SYNOPSIS"
.sp
.ft B
.nf

C++:

#include <libgpsmm>

.fi
.ft
.HP \w'struct\ gps_data_t\ *open('u
.BI "struct gps_data_t *open(char\ *" "host" ", char\ *" "port" ");"
.HP \w'struct\ gps_data_t\ *open('u
.BI "struct gps_data_t *open(void);"
.HP \w'struct\ gps_data_t\ *send('u
.BI "struct gps_data_t *send(char\ *" "request" ");"
.HP \w'struct\ gps_data_t\ *read('u
.BI "struct gps_data_t *read(void);"
.HP \w'struct\ gps_data_t\ *waiting('u
.BI "struct gps_data_t *waiting(int);"
.HP \w'struct\ gps_data_t\ *stream('u
.BI "struct gps_data_t *stream(unsigned\ int" "flags" ");"
.SH "DESCRIPTION"
.PP
\fBlibgpsmm and libQgpsmm\fR
are mere wrappers over
\fBlibgps\fR\&. The important difference between the libraries is that libgpsmm is targeted at C++ applications and contained in
\fBlibgps\fR, while libQgpsmm is platform independent by using QTcpSocket to connect to
\fBgpsd\fR
and shipped as an additional library due to the necessary linking to QT\&. Method names are the same as the analogue C functions\&. For a detailed description of the functions please read
\fBlibgps\fR(3)\&.
\fBopen()\fR
must be called after class constructor and before any other method (\fBopen()\fR
is not inside the constructor since it may fail, however constructors have no return value)\&. The analogue of the C function
\fBgps_close()\fR
is in the destructor\&.
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBgps\fR(1),
\fBlibgps\fR(3)\&.
.SH "AUTHOR"
.PP
Alfredo Pironti <alfredio@users\&.sourceforge\&.net>\&.
