'\" t
.\"     Title: ppscheck
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 28 Jul 2016
.\"    Manual: GPSD Documentation
.\"    Source: The GPSD Project
.\"  Language: English
.\"
.TH "PPSCHECK" "8" "28 Jul 2016" "The GPSD Project" "GPSD Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ppscheck \- tool to check a serial port for PPS
.SH "SYNOPSIS"
.HP \w'\fBppscheck\fR\ 'u
\fBppscheck\fR [\-h] [\-V] \fIdevice\fR
.SH "DESCRIPTION"
.PP
ppscheck watches a specified serial port for transitions that might be PPS\&. It looks for changes in handshake lines CD, RI, and CTS by running ioctl(\&.\&.\&.\&., TIOCMIWAIT, \&.\&.\&.) in a loop\&. When it sees a state change it emits a timestamped line of output dumping the state of the handshake signals\&. It\*(Aqs useful for checking whether a device is emitting PPS\&.
.PP
To check the first serial port do this:
.sp
.if n \{\
.RS 4
.\}
.nf
ppscheck /dev/ttyS0
.fi
.if n \{\
.RE
.\}
.PP
ppscheck is not intended for routine use, but rather for diagnostic purposes\&. Once you have verified a particular device can output PPS signals you will never need to use it again on that device\&.
.PP
The program accepts the following options:
.PP
\-h
.RS 4
Display help message and terminate\&.
.RE
.PP
\-V
.RS 4
Dump version and exit\&.
.RE
.PP
The "device" argument should be the pathname of a device\&. It will be the device monitored\&.
.PP
Each output line is the second and nanosecond parts of a timestamp followed by the names of the handshake signals then asserted\&. Off transitions may generate lines with no signals aserted\&.
.PP
If you don\*(Aqt see output within a second, use gpsmon or some other equivalent tool to check that your device has a satellite lock and is getting 3D fixes before giving up on the possibility of PPS\&.
.PP
Check your cable\&. Cheap DB9 to DB9 cables such as those issued with UPSes often carry TXD/RXD/GND only, omitting handshake lines such as DCD\&. Suspect this especially if the cable jacket looks too skinny to hold more than three leads!
.PP
Most GPS that have built in USB do not support PPS\&. When in doubt, contact the vendor for confirmation that your device does supply PPS\&.
.SH "RETURN VALUES"
.PP
1 if the device counld not be opened\&. 0 otherwise
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8)\&.
.SH "AUTHOR"
.PP
Eric S\&. Raymond
<esr@thyrsus\&.com>\&.
