'\" t
.\"     Title: zerk
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 18 Sep 2018
.\"    Manual: GPSD Documentation
.\"    Source: The GPSD Project
.\"  Language: English
.\"
.TH "ZERK" "1" "18 Sep 2018" "The GPSD Project" "GPSD Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
zerk \- All purpose GREIS fitting
.SH "SYNOPSIS"
.HP \w'\fBzerk\fR\ 'u
\fBzerk\fR [\-?] [\-c\ \fIcommand\fR] [\-d\ \fIdisable\fR] [\-e\ \fIenable\fR] [\-f\ \fIfile/device\fR] [\-h] [\-O\ \fIoaf\fR] [\-p\ \fIpreset\fR] [\-R\ \fIrawfile\fR] [\-r] [\-S\ \fIsetspeed\fR] [\-s\ \fIspeed\fR] [\-V] [\-v\ \fIverbosity\fR] [\-W] [\-w\ \fIwait\fR] [[server[:port[:device]]]]
.SH "DESCRIPTION"
.PP
zerk
is an all purpose GREIS fitting\&. If you do not have a Javad GPS that speaks the GREIS protocol then you can stop reading now\&.
.PP
This tool operates with your Javad GPS at a very low level\&. To understand
zerk
you must first be familiar with your Javad GPS and the documentation for the GREIS protocol\&.
\m[blue]\fBGREIS (GNSS Receiver External Interface Specification) Guide\fR\m[]\&\s-2\u[1]\d\s+2\&.
.PP
zerk
can decode common GREIS messages, poll the GPS status, enable and disable GPS features, and send user generated commands to the GPS\&. It can read GREIS messages from a file\&. It can read and write directly through a serial device, or through a running gpsd instance\&.
.SH "OPTIONS"
.PP
The program accepts the following options:
.PP
\-c COMMAND
.RS 4
Send a text string to the GPS\&. Accepts one parameter, COMMAND, the command string to send to the GPS\&. The string is sent verbatim, except a newline is appended\&.
.RE
.PP
\-d OPTION
.RS 4
Disable an option in the GPS\&. Accepts one parameter, OPTION, the option to disable\&.
zerk
will exit after the GPS acknowledges the command, unless the \-W is given\&.
.PP
4HZ
.RS 4
Disable basic GREIS messages at 4Hz\&. The messages are: [RT], [UO], [GT], [PV], [SG], [DP], [SI], [EL], [AZ], [EC], [SS], and [ET]
.RE
.PP
COMPASS
.RS 4
Disable use of the COMPASS (BeiDou) constellation\&.
.RE
.PP
CONS
.RS 4
Disable use of all constellations\&.
.RE
.PP
DEFMSG
.RS 4
Disable the default message set (/dev/msg) at 1Hz\&.
.RE
.PP
GALILEO
.RS 4
Disable use of the GALILEO constellation\&.
.RE
.PP
GLONASS
.RS 4
Disable use of the GLONASS constellation\&.
.RE
.PP
GPS
.RS 4
Disable use of the GPS constellation\&.
.RE
.PP
IPR
.RS 4
Disable all Integer Pseudo Range messages\&. These are [rx], [rc], [r1], [r2], [r3], [r5], [rl]\&.
.RE
.PP
IRNSS
.RS 4
Disable use of the IRNSS constellation\&.
.RE
.PP
NMEA
.RS 4
Disable basic NMEA 4\&.1e messages at 4Hz\&. The messages are GBS, GGA, GSA, GST, GSV, RMC, VTG, and ZDA\&.
.RE
.PP
QZSS
.RS 4
Disable use of the QZSS constellation\&.
.RE
.PP
SBAS
.RS 4
Disable use of the SBAS constellation\&.
.RE
.PP
SNR
.RS 4
Disable all SNR messages, except [EC]\&. The messages disabled are: [E1], [E2], [E3], [E5], [El]\&.
.RE
.RE
.PP
\-e OPTION
.RS 4
Enable an option in the GPS\&. Accepts one parameter, OPTION, the option to enable\&.
zerk
will exit after the GPS acknowledges the command, unless the \-W is given\&. \-e accepts the same OPTIONs as \-d, except the action is to enable the option\&.
.RE
.PP
\-f FILE
.RS 4
Connect to a file or device\&. Accepts one parameter, FILE, the file or device to open\&. Files are opened read\-only\&. Character devices are opened read/write, unless the \-r parameter is given\&. Requires the pyserial module\&.
.RE
.PP
\-h
.RS 4
Makes
zerk
print a usage message and exit\&.
.RE
.PP
\-O OAF
.RS 4
Load an Option Authorization File (OAF) into the GPS\&. Accepts one parameter, OAF, command file to read\&. The OAF is just a special case of a \&.jpo (GREIS command file)\&. \-O will send any valid \&.jpo file to the GPS\&.
.RE
.PP
\-p PRESET
.RS 4
Send a preset command the GPS\&. Accepts one parameter, PRESET, the name of the command to send\&.
zerk
will exit after the GPS acknowledges the command, unless the \-W is given\&.
.PP
COLDBOOT
.RS 4
Coldboot the GPS\&.
.RE
.PP
CONS
.RS 4
Poll the enabled constellations\&.
.RE
.PP
DM
.RS 4
Disable all periodic GREIS messages\&.\&.
.RE
.PP
ID
.RS 4
Poll the receiver ID\&.
.RE
.PP
IPR
.RS 4
Poll all Integer Pseudo Range messages\&. These are [rx], [rc], [r1], [r2], [r3], [r5], [rl]\&.
.RE
.PP
OAF
.RS 4
Poll all OAF options\&.
.RE
.PP
RESET
.RS 4
Reset (reboot) the GPS\&.
.RE
.PP
SERIAL
.RS 4
Poll receiver serial number\&.
.RE
.PP
SNR
.RS 4
Poll all Signal to Noise Ratio (SNR) messages\&. [EC], [E1], [E2], [E3], [E5], [El]\&.
.RE
.PP
VENDOR
.RS 4
Poll GPS vendor\&.
.RE
.PP
VER
.RS 4
Poll GPS version\&.
.RE
.RE
.PP
\-r
.RS 4
Read only\&. Do not send anything to the GPS\&.
.RE
.PP
\-R RAW
.RS 4
Save all raw data from the GPS into the file RAW\&.
.RE
.PP
\-S SPEED
.RS 4
Configure the GPS serial speed to SPEED bps\&.
.RE
.PP
\-s SPEED
.RS 4
Set local serial port speed to SPEED bps\&. Default 115,200 bps\&.
.RE
.PP
\-V
.RS 4
Print
zerk
version and exit\&.
.RE
.PP
\-v VERBOSITY
.RS 4
Set verbosity level to VERBOSITY\&. Verbosity can be from 0 (very quiet), to 4 (very noisy)\&. Default 2\&.
.RE
.PP
\-v VERBOSITY
.RS 4
Set verbosity level to VERBOSITY\&. Verbosity can be from 0 (very quiet), 2 (decode messages), to 4 (very noisy)\&. Default 1\&.
.RE
.PP
\-W
.RS 4
Force waiting the entire wait time\&. No early exit for completion of \-d, \-e or \-p command\&.
.RE
.PP
\-w WAIT
.RS 4
Wait for WAIT seconds before exiting\&. Will exit early on command completion of \-d, \-e or \-p command, unless \-W is given\&. Default 2\&.0 second\&.
.RE
.PP
[server[:port[:device]]]
.RS 4
By default,
zerk
collects data from all compatible devices on localhost, using the default GPSD port 2947\&. An optional argument may specify a server to get data from\&. A colon\-separated suffix is taken as a port number\&. If there is a second colon\-separated suffix, that is taken as a specific device name to be watched\&. Further details on the
\fBgps\fR(1)
man page\&.
.RE
.PP
\-?
.RS 4
Makes
zerk
print a usage message and exit\&.
.RE
.SH "ENVIRONMENT"
.PP
Options can be placed in the ZERKOPTS environment variable\&. ZERKOPTS is processed before the CLI options\&.
.SH "EXAMPLES"
.PP
Print current Javad serial portC of GPS connected to local running gpsd::
.sp
.if n \{\
.RS 4
.\}
.nf
 zerk \-c "print,/cur/term"
.fi
.if n \{\
.RE
.\}
.PP
Decode raw log file:
.sp
.if n \{\
.RS 4
.\}
.nf
zerk \-r \-f greis\-binary\&.log \-v 2
.fi
.if n \{\
.RE
.\}
.PP
Change GPS port speed of device on /dev/ttyAMA0 to 230,400 bps::
.sp
.if n \{\
.RS 4
.\}
.nf
zerk \-S 230400 \-f /dev/ttyAMA0
.fi
.if n \{\
.RE
.\}
.PP
Watch entire GPS reset cycle:
.sp
.if n \{\
.RS 4
.\}
.nf
zerk \-p RESET \-v 2 \-w 20 \-W
.fi
.if n \{\
.RE
.\}
.PP
Poll SVs Status:
.sp
.if n \{\
.RS 4
.\}
.nf
zerk \-W \-w 2 \-v 2 \-c "out,,jps/{CS,ES,GS,Is,WS,QS}"
.fi
.if n \{\
.RE
.\}
.sp
Dump gpsd data from remote server:
.sp
.if n \{\
.RS 4
.\}
.nf
zerk \-v 2 \-w 5 server
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
zerk
is written to conform to the official Javad documentation for the GREIS protocol\&.
\m[blue]\fBGREIS (GNSS Receiver External Interface Specification) Guide\fR\m[]\&\s-2\u[1]\d\s+2\&.
.PP
\fBgpsd\fR(8),
\fBgps\fR(1),
\fBcgps\fR(1),
\fBxgps\fR(1),
\fBgpsfake\fR(1),
\fBgpsctl\fR(1),
\fBgpscat\fR(1),
\fBgnuplot\fR(1)\&.
.SH "AUTHOR"
.PP
Gary E\&. Miller<gem@rellim\&.com>
.SH "NOTES"
.IP " 1." 4
GREIS (GNSS Receiver External Interface Specification) Guide
.RS 4
\%http://www.javad.com/downloads/javadgnss/manuals/GREIS/GREIS_Reference_Guide.pdf
.RE
