#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/prerm.d && run-parts --arg="6.1.8-16ton" --arg="/boot/vmlinuz-6.1.8-16ton" /etc/kernel/prerm.d
exit 0
