/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for cifs_spnego_negtokeninit
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder cifs_spnego_negtokeninit_decoder;

extern int cifs_gssapi_this_mech(void *, size_t, unsigned char, const void *, size_t);
extern int cifs_neg_token_init_mech_type(void *, size_t, unsigned char, const void *, size_t);

